#include "color_handler.h"

void InitGameColors() {
  init_color(CUSTOM_COLOR_PINK, 980, 600, 790);
  init_color(CUSTOM_COLOR_ORANGE, 1000, 392, 0);
  init_color(CUSTOM_COLOR_BROWN, 592, 337, 290);
  init_color(CUSTOM_COLOR_SILVER, 752, 752, 752);
  init_color(CUSTOM_COLOR_YELLOW, 1000, 843, 0);
  init_color(CUSTOM_COLOR_PURPLE, 500, 0, 500);
  init_color(CUSTOM_COLOR_RED, 1000, 0, 0);
  init_color(CUSTOM_COLOR_GREEN, 0, 500, 0);
  init_color(CUSTOM_COLOR_BLUE, 25, 25, 830);
  init_color(CUSTOM_COLOR_PREDICT, 150, 150, 150);
  init_color(CUSTOM_COLOR_GRAY, 500, 500, 500);

  init_pair(RED_COLOR_PAIR_INDEX, CUSTOM_COLOR_RED, CUSTOM_COLOR_RED);
  init_pair(ORANGE_COLOR_PAIR_INDEX, CUSTOM_COLOR_ORANGE, CUSTOM_COLOR_ORANGE);
  init_pair(YELLOW_COLOR_PAIR_INDEX, CUSTOM_COLOR_YELLOW, CUSTOM_COLOR_YELLOW);
  init_pair(PINK_COLOR_PAIR_INDEX, CUSTOM_COLOR_PINK, CUSTOM_COLOR_PINK);
  init_pair(GREEN_COLOR_PAIR_INDEX, CUSTOM_COLOR_GREEN, CUSTOM_COLOR_GREEN);
  init_pair(BLUE_COLOR_PAIR_INDEX, CUSTOM_COLOR_BLUE, CUSTOM_COLOR_BLUE);
  init_pair(PURPLE_COLOR_PAIR_INDEX, CUSTOM_COLOR_PURPLE, CUSTOM_COLOR_PURPLE);
  init_pair(PREDICT_COLOR_PAIR_INDEX, CUSTOM_COLOR_PREDICT,
            CUSTOM_COLOR_PREDICT);

  init_pair(RECORD_1_COLOR_PAIR_INDEX, CUSTOM_COLOR_YELLOW, COLOR_BLACK);
  init_pair(RECORD_2_COLOR_PAIR_INDEX, CUSTOM_COLOR_SILVER, COLOR_BLACK);
  init_pair(RECORD_3_COLOR_PAIR_INDEX, CUSTOM_COLOR_BROWN, COLOR_BLACK);
  init_pair(RECORD_4_5_COLOR_PAIR_INDEX, CUSTOM_COLOR_GRAY, COLOR_BLACK);

  init_pair(INIT_COLOR_PAIR, COLOR_BLACK, COLOR_BLACK);
}
