#ifndef C7_BRICK_GAME_V_1_0_1_BRICK_GAME_TETRIS_TIME_HANDLER_H_
#define C7_BRICK_GAME_V_1_0_1_BRICK_GAME_TETRIS_TIME_HANDLER_H_

#include <sys/time.h>

long long GetTimeInMS();

#endif  // C7_BRICK_GAME_V_1_0_1_BRICK_GAME_TETRIS_TIME_HANDLER_H_
